import JSZip from "jszip";

import { FONT_OPTIONS } from "@/data/fonts";
import { resolveTokenReference } from "@/lib/generator";
import {
  GeneratedSystem,
  PALETTE_NAMES,
  SCALE_STEPS,
  SEMANTIC_TOKEN_NAMES,
  ThemeSemanticTokens,
} from "@/types/design-system";

function semanticBlock(name: string, tokens: ThemeSemanticTokens, system: GeneratedSystem) {
  return SEMANTIC_TOKEN_NAMES.map((token) => {
    const cssName = token.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`);
    const value = resolveTokenReference(tokens[token], system.palettes);

    return `  --ds-${cssName}: ${value};`;
  }).join("\n");
}

function paletteLines(system: GeneratedSystem) {
  return PALETTE_NAMES.flatMap((paletteName) =>
    SCALE_STEPS.map((step) => `  --ds-${paletteName}-${step}: ${system.palettes[paletteName][step]};`),
  ).join("\n");
}

function typographyLines(system: GeneratedSystem) {
  return [
    `  --ds-font-heading: ${system.typography.headingFont};`,
    `  --ds-font-body: ${system.typography.bodyFont};`,
    ...Object.entries(system.typography.scale).flatMap(([key, token]) => [
      `  --ds-type-${key}-size: ${token.size};`,
      `  --ds-type-${key}-line-height: ${token.lineHeight};`,
      `  --ds-type-${key}-weight: ${token.weight};`,
      ...(token.letterSpacing ? [`  --ds-type-${key}-tracking: ${token.letterSpacing};`] : []),
    ]),
  ].join("\n");
}

function chromeLines(system: GeneratedSystem) {
  return [
    ...Object.entries(system.radius).map(([key, value]) => `  --ds-radius-${key}: ${value};`),
    ...Object.entries(system.shadows).map(([key, value]) => `  --ds-shadow-${key}: ${value};`),
    `  --ds-density: ${system.density};`,
  ].join("\n");
}

export function buildThemeCss(system: GeneratedSystem) {
  return `:root {\n${paletteLines(system)}\n${typographyLines(system)}\n${chromeLines(system)}\n${semanticBlock("light", system.lightTokens, system)}\n}\n\n[data-theme="dark"] {\n${semanticBlock("dark", system.darkTokens, system)}\n}\n`;
}

export function buildTailwindThemeCss() {
  return `@import "tailwindcss";\n\n@theme inline {\n  --color-background: var(--ds-background);\n  --color-foreground: var(--ds-foreground);\n  --color-surface: var(--ds-surface);\n  --color-surface-elevated: var(--ds-surface-elevated);\n  --color-text-primary: var(--ds-text-primary);\n  --color-text-secondary: var(--ds-text-secondary);\n  --color-text-muted: var(--ds-text-muted);\n  --color-border-default: var(--ds-border-default);\n  --color-border-strong: var(--ds-border-strong);\n  --color-action-primary: var(--ds-action-primary);\n  --color-action-secondary: var(--ds-action-secondary);\n  --color-focus-ring: var(--ds-focus-ring);\n  --color-success: var(--ds-success);\n  --color-warning: var(--ds-warning);\n  --color-danger: var(--ds-danger);\n  --font-sans: var(--ds-font-body);\n  --font-display: var(--ds-font-heading);\n  --radius-sm: var(--ds-radius-sm);\n  --radius-md: var(--ds-radius-md);\n  --radius-lg: var(--ds-radius-lg);\n  --radius-xl: var(--ds-radius-xl);\n  --shadow-sm: var(--ds-shadow-sm);\n  --shadow-md: var(--ds-shadow-md);\n  --shadow-lg: var(--ds-shadow-lg);\n}\n`;
}

export function buildTokensJson(system: GeneratedSystem, brandName: string) {
  const heading = FONT_OPTIONS.find((font) => font.cssVariable === system.typography.headingFont)?.family ?? "Custom";
  const body = FONT_OPTIONS.find((font) => font.cssVariable === system.typography.bodyFont)?.family ?? "Custom";

  return JSON.stringify(
    {
      meta: {
        product: "Tailwind Design System Generator",
        brandName,
      },
      palettes: system.palettes,
      semantics: {
        light: system.lightTokens,
        dark: system.darkTokens,
      },
      typography: {
        headingFont: heading,
        bodyFont: body,
        scale: system.typography.scale,
      },
      radius: system.radius,
      shadows: system.shadows,
      density: system.density,
    },
    null,
    2,
  );
}

export function buildReadme(brandName: string) {
  return `# ${brandName} Design Tokens\n\nThis package was generated by Tailwind Design System Generator.\n\n## Files\n- \`theme.css\` defines raw palette variables, semantic tokens, typography, radius, shadows, and density.\n- \`tailwind-theme.css\` maps those variables into Tailwind CSS v4 with \`@theme\`.\n- \`tokens.json\` provides the same values in JSON form for tooling.\n\n## Usage\n1. Import \`theme.css\` after your app styles.\n2. Import \`tailwind-theme.css\` anywhere Tailwind reads your theme layer.\n3. Toggle dark mode by adding \`data-theme="dark"\` on a parent element.\n`;
}

export async function buildZip(system: GeneratedSystem, brandName: string) {
  const zip = new JSZip();
  zip.file("tokens.json", buildTokensJson(system, brandName));
  zip.file("theme.css", buildThemeCss(system));
  zip.file("tailwind-theme.css", buildTailwindThemeCss());
  zip.file("README.md", buildReadme(brandName));

  return zip.generateAsync({ type: "blob" });
}

export function downloadTextFile(filename: string, contents: string, mimeType: string) {
  const blob = new Blob([contents], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
